namespace api.Enums
{
	public enum DeveloperRoleEnum
	{
		AI_ENGINEER,
		ANDROID_DEVELOPER,
		BACKEND_DEVELOPER,
		BLOCKCHAIN_DEVELOPER,
		DATA_SCIENTIST,
		DEVELOPER,
		DEVOPS_ENGINEER,
		FRONTEND_DEVELOPER,
		FULLSTACK_DEVELOPER,
		FULL_STACK_DEVELOPER,
		GAME_DEVELOPER,
		IOS_DEVELOPER,
		MOBILE_DEVELOPER,
		OTHER,
		PROJECT_MANAGER,
		QA_ENGINEER,
		SUPPORT_OPERATOR,
		WEB_DEVELOPER
	}

}